name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: "update modules"
      run: npm i

    - name: "build"
      run: npm run all

    - name: "check for uncommitted changes"
      run: |
        git diff --exit-code --stat dist/index.js \
        || (echo "##[error] Generated and committed dist/index.js'" \
            && exit 1)
