name: "Publish GitHub Action"
on:
  push:
    tags:    
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1